### ISSUE TITLE
Load dirtree in .emacs

### ISSUE THREAD

**Issue by onlyshk** [zk/emacs-dirtree#2]
Hello,

First of all thank you for dirtree. When i open my emacs, it's open with buffer witch was saved with last exit. I want to generate dirtree with this dirs.

What i must write in my .emacs? How can i user dirtree-in-buffer or dirtree in .emacs?

**Comment by zk** [comment]
Hey @onlyshk, I think you're going to need to add that functionality yourself. Feel free to open up a PR once you've got that.
